#!/usr/bin/env bash

set -e

unset CFLAGS CXXFLAGS SHAREDFLAGS

# Use libraries from Qsnake (except on OSX):
if [ "$(uname)" != "Darwin" ]; then
    export ATLAS="$SPKG_LOCAL"
    export BLAS="$SPKG_LOCAL"
    export LAPACK="$SPKG_LOCAL"
fi

export UMFPACK="$SPKG_LOCAL"

# This fixes an "undefined reference to `MAIN__'" linking error with gfortran:
if [ "$(uname)" = "Darwin" ]; then
    export LDFLAGS="-bundle -undefined dynamic_lookup"
else
    export LDFLAGS="-shared"
fi

cd src
python setup.py install
