#!/usr/bin/env bash

set -e

unset CFLAGS CXXFLAGS SHAREDFLAGS

export ATLAS="$SPKG_LOCAL"
export BLAS="$SPKG_LOCAL"
export LAPACK="$SPKG_LOCAL"
export UMFPACK="$SPKG_LOCAL"

cd src
python setup.py install
